# @format

version: '3'
services:
  api:
    image: gcr.io/project-elaichi/server-central-vm-image:latest
    ports:
      - '4000:5000'
    env_file:
      - .env
    volumes:
      - /opt/project-dates/logs:/app/logs
