name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
    - deploy

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GCE_INSTANCE: server-central-vm	  
  GCE_INSTANCE_ZONE: us-central1-a   
  

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    
    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    - name: Ignored Files Reveal
      run: |-
        echo "${{ secrets.ENV_CONFIG }}" > ./sources/env_encoded.txt
    - run: |-
        echo "${{ secrets.ADMIN_SDK }}" > ./sources/project-elaichi_encoded.txt
    - run: |- 
        cd ./sources && base64 --decode -i env_encoded.txt > .env
    - run: |- 
        cd ./sources && base64 --decode -i project-elaichi_encoded.txt > project-elaichi.json
    - run: |-
        cat ./sources/project-elaichi.json ./sources/.env      
            
    #Build the Docker image
    - name: Build
      run: |-
        docker build --tag "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image" ./sources
   #Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:latest"   
    - run: |-
        gcloud config set project $PROJECT_ID
    - run: |-
        gcloud compute ssh server-central-vm --zone=$GCE_INSTANCE_ZONE --command="sudo bash /home/sa_106760886337188762615/startup.sh"
